# Introduced in: 278fc6e903834acfb37565795a196b85282560b0
# "A common pattern in our Gemfiles is to declare a gem
# differently if we're in a dev mode or not. For example
#
# if ENV['API_DEV']
#   gem 'gds-api-adapters', path: '../gds-api-adapters'
# else
#   gem 'gds-api-adapters', "~> 50.8.0"
# end"
# TODO: see if we can remove this (no longer valid??)
Bundler/DuplicatedGem:
  Enabled: false
