AllCops:
  NewCops: disable
  Exclude:
    - 'bin/**'
    - 'config.ru'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/201*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

  DisplayCopNames:
    Description: 'Display cop names in offense messages'
    Enabled: true

  ExtraDetails:
    Description: 'Display extra details in offense messages.'
    Enabled: true

  DisplayStyleGuide:
    Description: 'Display style guide URLs in offense messages.'
    Enabled: true

inherit_from:
  - bundler.yml
  - layout.yml
  - metrics.yml
  - naming.yml
  - style.yml
  - rake.yml
