# Part of the orignal GDS styleguide
# "Use empty lines between defs and to break up a method into logical paragraphs."
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#general
Layout/EmptyLineBetweenDefs:
  Description: Use empty lines between defs.
  Enabled: true
  AllowAdjacentOneLineDefs: false

# https://github.com/alphagov/govuk-lint/pull/7
# "There are occasions where following this rule forces you to make the
# code less readable. This is particularly the case for tests where method
# names form the test descriptions. Keeping test descriptions under a
# certain length can force them to become cryptic."
Layout/LineLength:
  Description: Limit lines to 80 characters.
  Enabled: false

# TODO: unclear why this is here!
# https://github.com/alphagov/govuk-lint/commit/5e42ec5690e3d4cc8fff44d0b0268c8e581c423a
Layout/MultilineMethodCallIndentation:
  Enabled: false

# Part of the orignal GDS styleguide
# "Outdent private etc"
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#classes
Layout/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  Enabled: true
  EnforcedStyle: outdent

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling this with
# "EnforcedStyle: consistent".
Layout/FirstArrayElementIndentation:
  Description: >-
    Checks the indentation of the first element in an array
    literal.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling this with
# "EnforcedStyle: consistent".
Layout/FirstHashElementIndentation:
  Description: 'Checks the indentation of the first key in a hash literal.'
  Enabled: false

# Introduced in: 9b2a744ab119d7797aaf423abcec914360f4208e
# "More lenient on multi-line operations"
# TODO: unclear why this is here!
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
