# TODO: unclear why this is here!
# https://github.com/alphagov/govuk-lint/pull/38
Layout/ClosingParenthesisIndentation:
  Description: 'Checks the indentation of hanging closing parentheses.'
  Enabled: false

# Part of the orignal GDS styleguide
# "Use empty lines between defs and to break up a method into logical paragraphs."
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#general
Layout/EmptyLineBetweenDefs:
  Description: Use empty lines between defs.
  Enabled: true
  AllowAdjacentOneLineDefs: false

# https://github.com/alphagov/govuk-lint/pull/7
# "There are occasions where following this rule forces you to make the
# code less readable. This is particularly the case for tests where method
# names form the test descriptions. Keeping test descriptions under a
# certain length can force them to become cryptic."
Layout/LineLength:
  Description: Limit lines to 80 characters.
  Enabled: false

# TODO: unclear why this is here!
# https://github.com/alphagov/govuk-lint/commit/5e42ec5690e3d4cc8fff44d0b0268c8e581c423a
Layout/MultilineMethodCallIndentation:
  Enabled: false

# Part of the orignal GDS styleguide
# "Outdent private etc"
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#classes
Layout/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  Enabled: true
  EnforcedStyle: outdent

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/HashAlignment:
  Description: >-
    Align the elements of a hash literal if they span more than
    one line.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/ParameterAlignment:
  Description: >-
    Align the parameters of a method call if they span more
    than one line.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/CommentIndentation:
  Description: 'Indentation of comments.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling this with
# "EnforcedStyle: consistent".
Layout/FirstArrayElementIndentation:
  Description: >-
    Checks the indentation of the first element in an array
    literal.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling this with
# "EnforcedStyle: consistent".
Layout/FirstHashElementIndentation:
  Description: 'Checks the indentation of the first key in a hash literal.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/LeadingCommentSpace:
  Description: 'Comments should start with a space.'
  Enabled: false

# Introduced in: 9b2a744ab119d7797aaf423abcec914360f4208e
# "More lenient on multi-line operations"
# TODO: unclear why this is here!
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/SpaceAroundKeyword:
  Description: 'Use spaces after if/elsif/unless/while/until/case/when.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/SpaceBeforeComment:
  Description: >-
    Checks for missing space between code and a comment on the
    same line.
  Enabled: false
