# Part of the orignal GDS styleguide
# "Outdent private etc"
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#classes
Layout/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  Enabled: true
  EnforcedStyle: outdent

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: conflicts with the original GDS styleguide
# "Avoid get/set method names"
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#naming
Naming/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Alias:
  Description: 'Use alias_method instead of alias.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/HashAlignment:
  Description: >-
    Align the elements of a hash literal if they span more than
    one line.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/ParameterAlignment:
  Description: >-
    Align the parameters of a method call if they span more
    than one line.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/ArrayJoin:
  Description: 'Use Array#join instead of Array#*.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Naming/AsciiIdentifiers:
  Description: 'Use only ascii symbols in identifiers.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Attr:
  Description: 'Checks for uses of Module#attr.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/BeginBlock:
  Description: 'Avoid the use of BEGIN blocks.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/BlockComments:
  Description: 'Do not use block comments.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Metrics/BlockNesting:
  Description: 'Avoid excessive block nesting'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/BlockDelimiters:
  Description: >-
    Avoid using {...} for multi-line blocks (multiline chaining is
    always ugly).
    Prefer {...} over do...end for single-line blocks.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/CaseEquality:
  Description: 'Avoid explicit use of the case equality operator(===).'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/CharacterLiteral:
  Description: 'Checks for uses of character literals.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

# TODO: duplicate (other-metrics.yml), remove
Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

# TODO: unclear why this is here!
# TODO: remove, as disabled by default
Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/ColonMethodCall:
  Description: 'Do not use :: for method call.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/CommentAnnotation:
  Description: >-
    Checks formatting of special comments
    (TODO, FIXME, OPTIMIZE, HACK, REVIEW).
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/CommentIndentation:
  Description: 'Indentation of comments.'
  Enabled: false

# Analog of: 736b3d295f88b9ba6676fc168b823535582388c2
# "Disable opinionated cops"
#
# We should avoid cops that are based on heuristics, since
# it's not clear what action to take to fix an issue.
Metrics/CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/PreferredHashMethods:
  Description: 'Checks for use of deprecated Hash methods.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# Documenting every class is a lot of effort and we don't
# expect to get any value from this. Another risk of adding
# more documentation is the potential for confusion if that
# documentation gets out-of-sync with the class/module.
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/DoubleNegation:
  Description: 'Checks for uses of double negation (!!).'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/EachWithObject:
  Description: 'Prefer `each_with_object` over `inject` or `reduce`.'
  Enabled: false

# Part of the original GDS styleguide
# "leave one blank line before the visibility modifier
# and one blank line below in order to emphasize that
# it applies to all methods below it"
# TODO: remove, as enabled by default!
Layout/EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  Enabled: true

# TODO: conflicts with gds-ruby-styleguide.rake!
# Layout/EmptyLines:
#  Description: "Don't use several empty lines in a row."
#  Enabled: true
Layout/EmptyLines:
  Description: "Keeps track of empty lines around expression bodies."
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/EmptyLiteral:
  Description: 'Prefer literals to Array.new/Hash.new/String.new.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/EndBlock:
  Description: 'Avoid the use of END blocks.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/EvenOdd:
  Description: 'Favor the use of Fixnum#even? && Fixnum#odd?'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Naming/FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Lint/FlipFlop:
  Description: 'Checks for flip flops'
  Enabled: false

# TODO: duplicate (other-excludes.yml), remove
Style/FormatString:
  Description: 'Enforce the use of Kernel#sprintf, Kernel#format or String#%.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/GlobalVars:
  Description: 'Do not introduce global variables.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# This can lead to excessively long lines. Consistent with
# disabling "Layout/LineLength".
#
# "There are occasions where following this rule forces you to make the
# code less readable."
Style/GuardClause:
  Description: 'Check for conditionals that can be replaced with guard clauses'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/IfWithSemicolon:
  Description: 'Never use if x; .... Use the ternary operator instead.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling this with
# "EnforcedStyle: consistent".
Layout/FirstArrayElementIndentation:
  Description: >-
    Checks the indentation of the first element in an array
    literal.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling this with
# "EnforcedStyle: consistent".
Layout/FirstHashElementIndentation:
  Description: 'Checks the indentation of the first key in a hash literal.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/LambdaCall:
  Description: 'Use lambda.call(...) instead of lambda.(...).'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/LeadingCommentSpace:
  Description: 'Comments should start with a space.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/LineEndConcatenation:
  Description: >-
    Use \ instead of + or << to concatenate two string literals at
    line end.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/MethodDefParentheses:
  Description: >-
    Checks if the method definitions have or don't have
    parentheses.
  Enabled: false

# Analog of: 736b3d295f88b9ba6676fc168b823535582388c2
# "Disable opinionated cops"
#
# We should avoid cops that are based on heuristics, since
# it's not clear what action to take to fix an issue.
Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/ModuleFunction:
  Description: 'Checks for usage of `extend self` in modules.'
  Enabled: false

# Introduced in: 9b2a744ab119d7797aaf423abcec914360f4208e
# "More lenient on multi-line operations"
# TODO: unclear why this is here!
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/NegatedIf:
  Description: >-
    Favor unless over if for negative conditions
    (or control flow or).
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/NegatedWhile:
  Description: 'Favor until over while for negative conditions.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Next:
  Description: 'Use `next` to skip iteration instead of a condition at the end.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/NilComparison:
  Description: 'Prefer x.nil? to x == nil.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/NonNilCheck:
  Description: 'Checks for redundant nil checks.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Not:
  Description: 'Use ! instead of not.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/NumericLiterals:
  Description: >-
    Add underscores to large numeric literals to improve their
    readability.
  Enabled: false

# Analog of: 736b3d295f88b9ba6676fc168b823535582388c2
# "Disable opinionated cops"
#
# We should avoid cops that are based on heuristics, since
# it's not clear what action to take to fix an issue.
Metrics/ParameterLists:
  Description: 'Avoid parameter lists longer than three or four parameters.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/PerlBackrefs:
  Description: 'Avoid Perl-style regex back references.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Naming/PredicateName:
  Description: 'Check the names of predicate methods.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Proc:
  Description: 'Use proc instead of Proc.new.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling with
# "EnforcedStyle: compact"
Style/RaiseArgs:
  Description: 'Checks the arguments passed to raise/fail.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/RedundantBegin:
  Description: "Don't use begin blocks when they are not needed."
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/RedundantException:
  Description: "Checks for an obsolete RuntimeException argument in raise/fail."
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/RedundantSelf:
  Description: "Don't use self where it's not needed."
  Enabled: false

# Analog of: 736b3d295f88b9ba6676fc168b823535582388c2
# "Disable opinionated cops"
#
# We should avoid cops that are based on heuristics, since
# it's not clear what action to take to fix an issue.
Style/RegexpLiteral:
  Description: >-
    Use %r for regular expressions matching more than
    `MaxSlashes` '/' characters.
    Use %r only for regular expressions matching more than
    `MaxSlashes` '/' character.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/RescueModifier:
  Description: 'Avoid using rescue in its modifier form.'
  Enabled: false

# Introduced in: 7aaebf4dbdf2a8d677b4000d3cd3512d4fb91e99
# "This is a relatively new Ruby feature and is not mentioned in the Style
# guide, so this commit disables it by default."
# TODO: unclear why this is here!
Style/SafeNavigation:
  Description: >-
    This cop transforms usages of a method call safeguarded by a check for the
    existance of the object to safe navigation (`&.`).
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/SelfAssignment:
  Description: 'Checks for places where self-assignment shorthand should have been used.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/Semicolon:
  Description: "Don't use semicolons to terminate expressions."
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/SignalException:
  Description: 'Checks for proper usage of fail and raise.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
# TODO: remove, as disabled by default!
Style/SingleLineBlockParams:
  Description: 'Enforces the names of some block params.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here! Suggest enabling with
# "AllowIfMethodIsEmpty: true" to accommodate Rails actions.
Style/SingleLineMethods:
  Description: 'Avoid single-line methods.'
  Enabled: false

# TODO: conflicts with other-lint.yml!
# Layout/SpaceBeforeFirstArg:
# Description: >-
#     Put a space between a method name and the first argument
#     in a method call without parentheses.
#  Enabled: true
Layout/SpaceBeforeFirstArg:
  Description: >-
    Checks that exactly one space is used between a method name
    and the first argument for method calls without parentheses.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/SpaceAroundKeyword:
  Description: 'Use spaces after if/elsif/unless/while/until/case/when.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Layout/SpaceBeforeComment:
  Description: >-
    Checks for missing space between code and a comment on the
    same line.
  Enabled: false

# Part of the original GDS styleguide
# "Use spaces [...] around { and before }"
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#general
# TODO: remove, as enabled by default!
Layout/SpaceInsideBlockBraces:
  Description: >-
    Checks that block braces have or don't have surrounding space.
    For blocks taking parameters, checks that the left brace has
    or doesn't have trailing space.
  Enabled: true

# Part of the original GDS styleguide
# "Use spaces [...] around { and before }"
# https://github.com/alphagov/styleguides/blob/6395a10d41c3938f4c147cda443fd83f854c3e7a/ruby.md#general
# TODO: remove, as enabled by default!
Layout/SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  Enabled: true

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/SpecialGlobalVars:
  Description: 'Avoid Perl-style global variables.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/RedundantCapitalW:
  Description: 'Checks for %W when interpolation is not needed.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/CommandLiteral:
  Description: 'Checks for %x when `` would do.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/VariableInterpolation:
  Description: >-
    Don't interpolate global, instance and class variables
    directly in strings.
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/WhenThen:
  Description: 'Use when x then ... for one-line cases.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/WhileUntilDo:
  Description: 'Checks for redundant do after while or until.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Style/WhileUntilModifier:
  Description: >-
    Favor modifier while/until usage when you have a
    single-line body.
  Enabled: false

# Introduced in: b171d652d3e434b74ddc621df3b5be24c49bc7e8
# This cop was added in preperation for a Ruby feature
# that is no longer likely to become part of the language.
# https://github.com/rubocop-hq/rubocop/issues/7197
Style/FrozenStringLiteralComment:
  Enabled: false
