AllCops:
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - "**/spec/**/*"
  ExcludedMethods: ["namespace"]

Bundler/DuplicatedGem:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# These can result in false positives
Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
