##################### Rails ##################################

# By default Rails is switched off so this can be used by non-Rails apps,
# this can be enabled in a local .rubocop.yml file

require: rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/201*'

Rails:
  Enabled: true

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Rails/HasAndBelongsToMany:
  Description: 'Prefer has_many :through to has_and_belongs_to_many.'
  Enabled: false

# Introduced in: c69a7eb3af955d6c4c0cf0c3cec8e9f330c74429
# TODO: unclear why this is here!
Rails/Output:
  Description: 'Checks for calls to puts, print, etc.'
  Enabled: false

# Introduced in: 91d7bf4895db12727582ad7bf47bdcb20ab178f7
# TODO: unclear (in any real detail) why this is here!
Rails/SkipsModelValidations:
  Description: 'Avoid methods that skip model validations.'
  Enabled: false
