##################### Rails ##################################

# By default Rails is switched off so this can be used by non-Rails apps,
# this can be enabled in a local .rubocop.yml file

require: rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/201*'

Rails:
  Enabled: true

# We commonly print output in Ruby code that has been
# extracted from a Rake task in 'lib/'.
Rails/Output:
  Exclude:
    - 'lib/**/*.rb'

# Introduced in: 91d7bf4895db12727582ad7bf47bdcb20ab178f7
# TODO: unclear (in any real detail) why this is here!
Rails/SkipsModelValidations:
  Description: 'Avoid methods that skip model validations.'
  Enabled: false
